Django modified structure, and recieves a played match replay
MMandirola/Overmind pull request #15
Opened 2018-09-24 08:31 UTC by bcattaneo

Fixes #12

2018-09-24 10:36 UTC, MMandirola requested changes

2018-09-24 10:36 UTC, MMandirola commented on Overmind/settings.py
> +DATABASES = {
Postgresql configuration, "psicopg2"

2018-09-24 10:36 UTC, MMandirola commented on Overmind/urls.py
>  """Overmind URL Configuration
Cleanup boilerplate comment

2018-09-24 10:36 UTC, MMandirola commented on Replays/prueba5.SC2Replay
> +hola
Add Replays/* to .gitignore

2018-09-24 10:36 UTC, MMandirola commented on api/admin.py
> +from django.contrib import admin
Add admin config to watch replay records on django admin

2018-09-24 10:36 UTC, MMandirola commented on api/models.py
> +        #return '%s %s' % (self.title, self.base64_file)
Cleanup

2018-09-24 10:36 UTC, MMandirola commented on api/resources.py
> +import base64
Move to views.py

2018-09-24 10:36 UTC, MMandirola commented on api/tests.py
> +
Add some tests

2018-09-24 10:36 UTC, MMandirola commented on api/resources.py
> +import base64
Add tastypie and django==2.1 to a requirements.txt file

2018-09-26 19:03 UTC, MMandirola requested changes

2018-09-26 19:03 UTC, MMandirola commented on Replays/prueba5.SC2Replay
> +hola
Remove replay file

2018-09-26 19:03 UTC, MMandirola commented on Overmind/settings.py
> +"""
Investigate Local settings pattern https://techstream.org/Bits/Local-Settings-in-django

2018-09-27 02:39 UTC, MMandirola approved these changes

2018-09-27 02:40 UTC, merged

2018-09-27 08:03 UTC, bcattaneo commented
Also fixes: #6 #1 #9